---
download_version: 2017.2.2
ga_release: true
pe_dist: el
pe_release: 7
pe_arch: x86_64
git_remote: 'https://github.com/puppetlabs-seteam/control-repo.git'
public_key:
priv_key:
s3publish: true
vmware_network: 'VM Network'
vmware_datastore: 'persistent1'
builds:
  - virtualbox
  - vmware
